Repository gjb2048/moodle-format_topcoll, pull requests merged in 2019-03, with the labels that each got.

#52 Fix for php unit test failure
  tests/courseformatrenderer_test.php
Labels: Requires improvement

#55 Spelling mistake in hidden settings field fixed.
  lib.php
Labels: Bug

#56 Improve accessibility of the open and close all buttons
  module.js
  renderer.php
  tests/courseformatrenderer_test.php
Labels: Enhancement
